### ISSUE TITLE
[SUBMISSION] Tips on being a civic technologist out of college

### ISSUE THREAD

**Issue by ResidentMario** [BetaNYC/ops-message#11]
Whilst in a minor career transition I wrote [a piece](https://blog.codingitforward.com/becoming-a-civic-technologist-out-of-college-4bcb37f9777c), published in *Coding It Forward*, of my advice to civic-minded tech folks in and/or just out of college. I though this might be good to link to in the next message. :)

**Comment by cmoscardi** [comment]
I think this was our first user submission that we didn't explicitly solicit! Woo! (Included)
