### ISSUE TITLE
[SUBMISSION] New MTA-specific software module of interest

### ISSUE THREAD

**Issue by ResidentMario** [BetaNYC/ops-message#14]
I wrote a Python module for transforming the GTFS-Realtime data of train trip updates that the MTA publishes into a table of historical trip arrival and departure times. This is [`gtfs-tripify`](https://github.com/ResidentMario/gtfs-tripify).

I thought this package would be of interest to the community, and this seems like a good place to share it.

**Comment by cmoscardi** [comment]
Thanks @ResidentMario ! Included

**Comment by cmoscardi** [comment]
One question, @ResidentMario - how would you like attribution? e.g. twitter handle, github username - let me know.

**Comment by cmoscardi** [comment]
(I think I put your github in)

**Comment by ResidentMario** [comment]
Yeah you did. Sorry for not responding, weirdly didn't see a ping for your message? Any attribution was fine obviously. :)
