### ISSUE TITLE
found a bad link in 07/27/2017 newsletter

### ISSUE THREAD

**Issue by jgravois** [BetaNYC/ops-message#2]
greetings! what an awesome newsletter y'all are shipping!

i just wanted to report a <sub><sup>tiny</sup></sub> problem i found in the most recent one.

http://us6.campaign-archive2.com/?u=2b506b76155e3fbdd93699baf&id=93e5edd147

> **Crowdsourcing the NYC Bike Map** ... The agencies that maintain the data will review edits made by citizens with the goal of improving the data and releasing more accurate datasets. [Here](http://%20https//mapping.nycyclist.com/).

~http://%20https//mapping.nycyclist.com/~ > https://mapping.nycyclist.com

**Comment by noneck** [comment]
@jgravois thanks for the heads up! And thanks for the ticket.

**Comment by cmoscardi** [comment]
To follow up: we'll be issuing a correction in the next newsletter, and will credit you for catching our mistake. 

Thanks again @jgravois ... also issue #1, :confetti_ball: :tada:  !!
