### ISSUE TITLE
Add @imcurtis to admin list

### ISSUE THREAD

**Issue by cmoscardi** [BetaNYC/ops-message#5]
@noneck , I can't assign issues to @imcurtis because he's not an admin

**Comment by noneck** [comment]
@imcurtis needs to accept the invite.

**Comment by cmoscardi** [comment]
@imcurtis, once you have, respond here and I'll do the thing for the submission triggering

**Comment by imcurtis** [comment]
Just accepted.

**Comment by cmoscardi** [comment]
Cool cool cool. Zapier only supports one assignee per trigger, so for now I'll stay on it. (I sent in a feature request).

 Probably generally good that you're an admin now, though.

**Comment by cmoscardi** [comment]
And just +1 you onto each one that comes in manually^^
